// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-0]
	_ = x[RightParen-1]
	_ = x[LeftBrace-2]
	_ = x[RightBrace-3]
	_ = x[Comma-4]
	_ = x[Dot-5]
	_ = x[Minus-6]
	_ = x[Plus-7]
	_ = x[Semicolon-8]
	_ = x[Slash-9]
	_ = x[Star-10]
	_ = x[Bang-11]
	_ = x[BangEqual-12]
	_ = x[Equal-13]
	_ = x[EqualEqual-14]
	_ = x[Greater-15]
	_ = x[GreaterEqual-16]
	_ = x[Less-17]
	_ = x[LessEqual-18]
	_ = x[Ident-19]
	_ = x[String-20]
	_ = x[Number-21]
	_ = x[And-22]
	_ = x[Class-23]
	_ = x[Else-24]
	_ = x[False-25]
	_ = x[Func-26]
	_ = x[For-27]
	_ = x[If-28]
	_ = x[Nil-29]
	_ = x[Or-30]
	_ = x[Return-31]
	_ = x[Super-32]
	_ = x[This-33]
	_ = x[True-34]
	_ = x[Var-35]
	_ = x[While-36]
	_ = x[EOF-37]
}

const _TokenType_name = "LeftParenRightParenLeftBraceRightBraceCommaDotMinusPlusSemicolonSlashStarBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualIdentStringNumberAndClassElseFalseFuncForIfNilOrReturnSuperThisTrueVarWhileEOF"

var _TokenType_index = [...]uint8{0, 9, 19, 28, 38, 43, 46, 51, 55, 64, 69, 73, 77, 86, 91, 101, 108, 120, 124, 133, 138, 144, 150, 153, 158, 162, 167, 171, 174, 176, 179, 181, 187, 192, 196, 200, 203, 208, 211}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
