// Code generated by "stringer -type=TokenType"; DO NOT EDIT.

package scanner

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[LeftParen-0]
	_ = x[RightParen-1]
	_ = x[LeftBrace-2]
	_ = x[RightBrace-3]
	_ = x[LeftBracket-4]
	_ = x[RightBracket-5]
	_ = x[Comma-6]
	_ = x[Dot-7]
	_ = x[Minus-8]
	_ = x[Plus-9]
	_ = x[Semicolon-10]
	_ = x[Slash-11]
	_ = x[Star-12]
	_ = x[Bang-13]
	_ = x[BangEqual-14]
	_ = x[Equal-15]
	_ = x[EqualEqual-16]
	_ = x[Greater-17]
	_ = x[GreaterEqual-18]
	_ = x[Less-19]
	_ = x[LessEqual-20]
	_ = x[Arrow-21]
	_ = x[Ident-22]
	_ = x[String-23]
	_ = x[Number-24]
	_ = x[And-25]
	_ = x[Class-26]
	_ = x[Else-27]
	_ = x[False-28]
	_ = x[Func-29]
	_ = x[For-30]
	_ = x[If-31]
	_ = x[Nil-32]
	_ = x[Or-33]
	_ = x[Return-34]
	_ = x[Super-35]
	_ = x[This-36]
	_ = x[True-37]
	_ = x[Var-38]
	_ = x[While-39]
	_ = x[EOF-40]
	_ = x[Static-41]
	_ = x[Colon-42]
}

const _TokenType_name = "LeftParenRightParenLeftBraceRightBraceLeftBracketRightBracketCommaDotMinusPlusSemicolonSlashStarBangBangEqualEqualEqualEqualGreaterGreaterEqualLessLessEqualArrowIdentStringNumberAndClassElseFalseFuncForIfNilOrReturnSuperThisTrueVarWhileEOFStaticColon"

var _TokenType_index = [...]uint8{0, 9, 19, 28, 38, 49, 61, 66, 69, 74, 78, 87, 92, 96, 100, 109, 114, 124, 131, 143, 147, 156, 161, 166, 172, 178, 181, 186, 190, 195, 199, 202, 204, 207, 209, 215, 220, 224, 228, 231, 236, 239, 245, 250}

func (i TokenType) String() string {
	if i < 0 || i >= TokenType(len(_TokenType_index)-1) {
		return "TokenType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _TokenType_name[_TokenType_index[i]:_TokenType_index[i+1]]
}
